# GitHub で Workflows として表示される名前
name: Action Test

# トリガーイベント
on:
  # git push をトリガーにする
  push:
    # main ブランチへの push が対象
    branches:
      - main

  # GitHub の Web ページ上で手動実行をトリガーにする
  workflow_dispatch:

# ジョブ (実行内容, 環境)
jobs:
  print-hello-world:

    # ジョブを実行するマシン
    runs-on: ubuntu-latest

    # 実行するコマンド
    steps:
      - name: build with asciidoctor
        run: asciidoctor ./src/index.adoc -o ./public/index.html

      # Pages にデプロイしてくれるリポジトリがあった
      - name: deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public